In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [3]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [4]:
df.shape

(569, 33)

In [5]:
df.drop(columns = ['id','Unnamed: 32'],inplace = True)

In [6]:
df.head(2)

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38           122.8     1001.0   
1         M        20.57         17.77           132.9     1326.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33            184.6   
1         0.1812  ...         24.99          23.41            158.8   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  

[2 rows x 31 columns]

In [8]:
X_train , X_test , y_train , y_test = train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size = 0.2)

In [13]:
type(X_train)

pandas.core.frame.DataFrame

In [14]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [15]:
X_train

array([[ 0.22659711,  0.23980449,  0.18615577, ..., -0.19509246,
        -0.86027882, -0.97628889],
       [-0.76909846, -1.04405473, -0.75669487, ..., -0.78353719,
        -1.74996866, -0.52938469],
       [ 0.16040926, -0.96639216,  0.17154764, ...,  0.38211197,
         0.38656251,  0.0351827 ],
       ...,
       [-1.26809734, -1.47605272, -1.14944496, ..., -0.10699284,
        -0.09654864,  2.82401607],
       [ 0.11436553,  0.54317388,  0.10810661, ...,  0.12085102,
         0.17769267, -0.84297326],
       [-1.57831694,  0.42668003, -1.54428192, ..., -1.31790697,
         0.10116021, -0.37555896]])

In [17]:
y_train

495    B
183    B
89     B
390    B
470    B
      ..
128    B
514    M
505    B
86     M
61     B
Name: diagnosis, Length: 455, dtype: object

In [18]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [19]:
y_train

array([0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1,
       1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1,

## Numpy arrays to PyTorch Tensors

In [20]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [22]:
X_train_tensor.shape

torch.Size([455, 30])

### Defining the Neural Network

In [30]:
class MySimpleNN():
    def __init__(self,X):
        self.weights = torch.rand(X.shape[1],1,dtype = torch.float64, requires_grad = True)
        self.bias = torch.rand(1,dtype = torch.float64, requires_grad = True)
    
    def forward(self,X):
        z = torch.matmul(X,self.weights) + self.bias
        y_pred = torch.sigmoid(z)
        return y_pred
    
    def loss_function(self, y_pred, y):
        # Clamp predictions to avoid log(0)
        epsilon = 1e-7
        y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

        # Calculate loss
        loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
        return loss

In [24]:
## Important Parameters
learning_rate = 0.01
epochs = 25

In [39]:
## Creating Model
model = MySimpleNN(X_train_tensor)

## Defining loop
for i in range(epochs):

    ## Forward pass
    y_pred = model.forward(X_train_tensor)

    ## Loss calculation
    loss = model.loss_function(y_pred , y_train_tensor)

    ## Backward pass
    loss.backward()

    ## Parameter updation
    with torch.no_grad():
        model.weights -= learning_rate * model.weights.grad
        model.bias -= learning_rate * model.bias.grad

    ## Zero gradients
    model.weights.grad.zero_()
    model.bias.grad.zero_()

    # print loss in each epoch
    print(f'Epoch : {i + 1}, Loss: {loss.item()}')
    

Epoch : 1, Loss: 4.067318899087165
Epoch : 2, Loss: 4.056949250638176
Epoch : 3, Loss: 4.04658492678465
Epoch : 4, Loss: 4.036202087078849
Epoch : 5, Loss: 4.025757221507495
Epoch : 6, Loss: 4.015317886731653
Epoch : 7, Loss: 4.004884142976147
Epoch : 8, Loss: 3.994456051138333
Epoch : 9, Loss: 3.984033672788621
Epoch : 10, Loss: 3.9735579822595755
Epoch : 11, Loss: 3.9629183777373416
Epoch : 12, Loss: 3.952284753932595
Epoch : 13, Loss: 3.9416571766247084
Epoch : 14, Loss: 3.9310357123198836
Epoch : 15, Loss: 3.9204115029919335
Epoch : 16, Loss: 3.9096355387586086
Epoch : 17, Loss: 3.898821263079605
Epoch : 18, Loss: 3.88796830691326
Epoch : 19, Loss: 3.8771219883360315
Epoch : 20, Loss: 3.8662599315207906
Epoch : 21, Loss: 3.855295644913607
Epoch : 22, Loss: 3.8443382465813136
Epoch : 23, Loss: 3.833275793577305
Epoch : 24, Loss: 3.8219403808436896
Epoch : 25, Loss: 3.810491670503122


In [40]:
model.weights

tensor([[ 0.4706],
        [ 0.4937],
        [ 0.4294],
        [ 0.8163],
        [ 0.7168],
        [-0.0591],
        [ 0.3800],
        [ 0.8644],
        [ 0.5693],
        [ 0.5392],
        [ 0.9293],
        [ 0.5723],
        [ 0.7250],
        [ 0.6110],
        [ 0.0553],
        [ 0.8923],
        [ 0.4925],
        [ 0.7644],
        [ 0.4096],
        [ 0.2573],
        [ 0.1469],
        [ 0.4261],
        [ 0.7816],
        [ 0.1085],
        [ 0.1858],
        [ 0.7314],
        [ 0.6231],
        [ 0.4007],
        [ 0.8797],
        [ 0.6329]], dtype=torch.float64, requires_grad=True)

In [41]:
model.bias

tensor([0.4813], dtype=torch.float64, requires_grad=True)

In [42]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.9).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.5467836260795593
